services:
  postgres:
    image: postgres:16
    container_name: pg-tenants
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pg_tenants_data:/var/lib/postgresql/data
volumes:
  pg_tenants_data:
